service: sadpandas-service
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  lambdaHashingVersion: 20201221
  iamRoleStatements: # permissions for all of your functions can be set here
    - Effect: Allow
      Action: # Gives permission to DynamoDB tables in a specific region
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - 'arn:aws:dynamodb:us-east-1:754180521889:table/ClubVideos'

custom:
  serverless-offline:
    httpPort: 8000

# package:
#   patterns:
#     - '!node_modules/**'

plugins:
  - serverless-offline

functions:
  hello:  #name of the function
    handler: handler.hello
    events:
      - http: 
          path: /
          method: ANY
      # - http: 
      #     path: /tags
      #     method: GET
      #     cors: true
      - http: 
          path: /{proxy+}
          method: ANY
          cors: true


    # events:
    #  - httpApi: 
    #     path: /users/create
    #     method: get
    # - schedule: rate(10 minutes)

    #example: 
    # - http:
    #     path: hello
    #     method: post
    #    在deploy时
    #    endpoints: POST - https://n5g4ytjhec.execute-api.us-east-2.amazonaws.com/dev/hello