service: sadpandas-service
frameworkVersion: '2'
provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-2
  lambdaHashingVersion: 20201221

custom:
  serverless-offline:
    httpPort: 8000

package:
  patterns:
    - '!node_modules/**'

plugins:
  - serverless-offline

functions:
  hello:  #name of the function
    handler: handler.hello
    events:
      - http: 
          path: /
          method: ANY
      - http: 
          path: /{proxy+}
          method: ANY


    # events:
    #  - httpApi: 
    #     path: /users/create
    #     method: get
    # - schedule: rate(10 minutes)

    #example: 
    # - http:
    #     path: hello
    #     method: post
    #    在deploy时
    #    endpoints: POST - https://n5g4ytjhec.execute-api.us-east-2.amazonaws.com/dev/hello